# Generated by Django 5.2 on 2025-05-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostReaction',
        ),
    ]
