# Generated by Django 5.2 on 2025-04-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
